import express from "express";
import {
  createLesson,
  getAllLessons,
  getLessonById,
  getLessonMaterialDownloadUrl,
  getLessonVideoDownloadUrl,
  updateLesson,
  deleteLesson,
} from "../controllers/LessonController.js";
import { protect, restrictTo } from "../middlewares/AuthMiddleware.js";
import { uploadLessonMedia } from "../middlewares/UploadMiddleware.js";
import { validate } from "../middlewares/ValidateMiddleware.js";
import {
  createLessonSchema,
  updateLessonSchema,
} from "../validators/LessonValidator.js";

const router = express.Router();

router.use(protect);

/*
  Lesson Routes
  - All routes require authentication (`protect`).
  - Creation and update are limited to teacher/school_admin/super_admin.
  - Uploads (material/video) go through `uploadLessonMedia` which validates types and sizes.
  - Material/video download endpoints return signed or direct URLs generated by controllers.
*/

router
  .route("/")
  .post(
    restrictTo("teacher", "school_admin", "super_admin"),
    uploadLessonMedia,
    validate(createLessonSchema),
    createLesson,
  )
  .get(getAllLessons);

router.route("/:id/material-download").get(getLessonMaterialDownloadUrl);
router.route("/:id/video-download").get(getLessonVideoDownloadUrl);

router
  .route("/:id")
  .get(getLessonById)
  .put(
    restrictTo("teacher", "school_admin", "super_admin"),
    uploadLessonMedia,
    validate(updateLessonSchema),
    updateLesson,
  )
  .delete(restrictTo("teacher", "school_admin", "super_admin"), deleteLesson);

export default router;
